### ISSUE TITLE
New version of Slider plugin with better UI

### ISSUE THREAD

**Issue by fthr** [vizorvr/vizor-create#79] opened 2015-06-09 14:43 UTC

**Comment by wd-vizor** [comment] 2015-06-10 01:56
What does "better UI" mean?

**Comment by afferently** [comment] 2015-06-10 11:14
First prototypes for new slider ui

In context of my completely made up editor experiment:
https://dl.dropboxusercontent.com/u/433261/slider/index.html

Isolated:
https://dl.dropboxusercontent.com/u/433261/slider/slider.html

Isolated with vzr's current palette
https://dl.dropboxusercontent.com/u/433261/slider/slider-vzr.html

**Comment by afferently** [comment] 2015-06-10 11:28
PS. The slider is fully working, click on it and try it!

**Comment by kschzt** [comment] 2015-06-10 11:34
couple notes:

- is it time to try it inside slider_generator.plugin.js yet? in the plugin frame, you'll basically have a table with two rows (header and content), and one cell in the content row (in addition to inputs and outputs) where the actual plugin UI is drawn. the behavior could be different!
- you'll need to have the range min/max inputs as well

looks great!

**Comment by afferently** [comment] 2015-06-10 11:46
Thank you! 

After talking to @fthr too, min and max inputs are next

**Comment by afferently** [comment] 2015-06-10 11:50
Also, integration shouldn't be too hard as at it's core currently its a styled input with a tiny js event attached to it. Obviously I'll have to add a few more events for the min and max to work though.

It should fit inside a table cell no problem. Ideally in the end a flexbox approach is better since the layout and order of ui items wouldn't then be fixed in mark up and could be changed simply with classes.

**Comment by juho** [comment] 2015-06-10 12:43
Looks really nice! My main issue is that I can't see the value of a slider output without clicking on it. Would it be possible to combine the number and the slider dot?

**Comment by afferently** [comment] 2015-06-10 14:03
@juho Unfortunately I think For min and max to work the value will have to be aside.

This is because, as @fthr mentioned to me in a convo, one example could be -111111 to 111111  which wouldn't fit.

Shame though!

**Comment by mattatgit** [comment] 2015-06-11 06:26
Definitely a graphical improvement, Derek. But if we can't see the numerical value in its default state there's not much point in having it because it defeats precise control. Also will it handle values for Position like +/-500 ? Look forward to seeing how you're going to handle max & min values.

**Comment by afferently** [comment] 2015-06-15 13:41
Here's my first iteration of a slider plugin: 
https://dl.dropboxusercontent.com/u/433261/slider-plugin/index.html.

It's shown in the editor concept for context.

Currently you can't type in a negative number but you can generate one using the counters next to each value. You can type in positive numbers though. This will be fixed in the next iteration along a more Vizor-ish colour palette.

If you find you can do weird things with it then please add steps to reproduce to this issue and I'll fix em', thanks!

**Comment by afferently** [comment] 2015-06-22 12:54
V3 iteration of the slider plugin built using riot and sporting "compact" mode.

To switch between compact and full modes just click the circle button located next to the slider's title.

https://dl.dropboxusercontent.com/u/433261/slider/v3/index.html

**Comment by wd-vizor** [comment] 2015-06-29 11:23
Closing for now, will re-open later.

**Closed by wd-vizor** 2015-06-29 11:23 UTC
Labels: Assembly, enhancement
